### ISSUE TITLE
Can I build and run it on Windows?

### ISSUE THREAD

**Issue by MateuszSadowski** [HipaccVX/HipaccVX#1]
Hi,

Is it possible to build and run the framework on Windows 10? I would like to use it for research on Varjo XR devices through OpenXR. Please, update the README with information on supported platforms.

**Comment by akifoezkan** [comment]
Hi,

thanks for the interest.
Provided installation is supported and tested on Ubuntu 18.04/20.04.

Provided CMake downloads and unpacks  Ubuntu version of Hipacc. By changing these lines, you can run HipaccVX on Windows as well.
